//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PhoneApp1.HoSTC_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HoSTC_Service.HoSTC_ServiceSoap")]
    public interface HoSTC_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLiveSecurity", ReplyAction="*")]
        System.IAsyncResult BeginGetLiveSecurity(PhoneApp1.HoSTC_Service.GetLiveSecurityRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.GetLiveSecurityResponse EndGetLiveSecurity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/fPUT_THROUGHT", ReplyAction="*")]
        System.IAsyncResult BeginfPUT_THROUGHT(PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponse EndfPUT_THROUGHT(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/fGetSTOCKROOM", ReplyAction="*")]
        System.IAsyncResult BeginfGetSTOCKROOM(PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponse EndfGetSTOCKROOM(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/fUserOnline", ReplyAction="*")]
        System.IAsyncResult BeginfUserOnline(PhoneApp1.HoSTC_Service.fUserOnlineRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.fUserOnlineResponse EndfUserOnline(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLiveTotalMKT", ReplyAction="*")]
        System.IAsyncResult BeginGetLiveTotalMKT(PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponse EndGetLiveTotalMKT(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetListStockWarning", ReplyAction="*")]
        System.IAsyncResult BeginGetListStockWarning(PhoneApp1.HoSTC_Service.GetListStockWarningRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.GetListStockWarningResponse EndGetListStockWarning(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetList30Stock", ReplyAction="*")]
        System.IAsyncResult BeginGetList30Stock(PhoneApp1.HoSTC_Service.GetList30StockRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp1.HoSTC_Service.GetList30StockResponse EndGetList30Stock(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveSecurityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveSecurity", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetLiveSecurityRequestBody Body;
        
        public GetLiveSecurityRequest() {
        }
        
        public GetLiveSecurityRequest(PhoneApp1.HoSTC_Service.GetLiveSecurityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLiveSecurityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool f_time;
        
        public GetLiveSecurityRequestBody() {
        }
        
        public GetLiveSecurityRequestBody(bool f_time) {
            this.f_time = f_time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveSecurityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveSecurityResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetLiveSecurityResponseBody Body;
        
        public GetLiveSecurityResponse() {
        }
        
        public GetLiveSecurityResponse(PhoneApp1.HoSTC_Service.GetLiveSecurityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLiveSecurityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveSecurityResult;
        
        public GetLiveSecurityResponseBody() {
        }
        
        public GetLiveSecurityResponseBody(string GetLiveSecurityResult) {
            this.GetLiveSecurityResult = GetLiveSecurityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fPUT_THROUGHTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fPUT_THROUGHT", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequestBody Body;
        
        public fPUT_THROUGHTRequest() {
        }
        
        public fPUT_THROUGHTRequest(PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fPUT_THROUGHTRequestBody {
        
        public fPUT_THROUGHTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fPUT_THROUGHTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fPUT_THROUGHTResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponseBody Body;
        
        public fPUT_THROUGHTResponse() {
        }
        
        public fPUT_THROUGHTResponse(PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fPUT_THROUGHTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fPUT_THROUGHTResult;
        
        public fPUT_THROUGHTResponseBody() {
        }
        
        public fPUT_THROUGHTResponseBody(string fPUT_THROUGHTResult) {
            this.fPUT_THROUGHTResult = fPUT_THROUGHTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fGetSTOCKROOMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fGetSTOCKROOM", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequestBody Body;
        
        public fGetSTOCKROOMRequest() {
        }
        
        public fGetSTOCKROOMRequest(PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fGetSTOCKROOMRequestBody {
        
        public fGetSTOCKROOMRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fGetSTOCKROOMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fGetSTOCKROOMResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponseBody Body;
        
        public fGetSTOCKROOMResponse() {
        }
        
        public fGetSTOCKROOMResponse(PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fGetSTOCKROOMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fGetSTOCKROOMResult;
        
        public fGetSTOCKROOMResponseBody() {
        }
        
        public fGetSTOCKROOMResponseBody(string fGetSTOCKROOMResult) {
            this.fGetSTOCKROOMResult = fGetSTOCKROOMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fUserOnlineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fUserOnline", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.fUserOnlineRequestBody Body;
        
        public fUserOnlineRequest() {
        }
        
        public fUserOnlineRequest(PhoneApp1.HoSTC_Service.fUserOnlineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class fUserOnlineRequestBody {
        
        public fUserOnlineRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fUserOnlineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fUserOnlineResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.fUserOnlineResponseBody Body;
        
        public fUserOnlineResponse() {
        }
        
        public fUserOnlineResponse(PhoneApp1.HoSTC_Service.fUserOnlineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fUserOnlineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fUserOnlineResult;
        
        public fUserOnlineResponseBody() {
        }
        
        public fUserOnlineResponseBody(string fUserOnlineResult) {
            this.fUserOnlineResult = fUserOnlineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveTotalMKTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveTotalMKT", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequestBody Body;
        
        public GetLiveTotalMKTRequest() {
        }
        
        public GetLiveTotalMKTRequest(PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLiveTotalMKTRequestBody {
        
        public GetLiveTotalMKTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveTotalMKTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveTotalMKTResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponseBody Body;
        
        public GetLiveTotalMKTResponse() {
        }
        
        public GetLiveTotalMKTResponse(PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLiveTotalMKTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveTotalMKTResult;
        
        public GetLiveTotalMKTResponseBody() {
        }
        
        public GetLiveTotalMKTResponseBody(string GetLiveTotalMKTResult) {
            this.GetLiveTotalMKTResult = GetLiveTotalMKTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListStockWarningRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListStockWarning", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetListStockWarningRequestBody Body;
        
        public GetListStockWarningRequest() {
        }
        
        public GetListStockWarningRequest(PhoneApp1.HoSTC_Service.GetListStockWarningRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListStockWarningRequestBody {
        
        public GetListStockWarningRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListStockWarningResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListStockWarningResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetListStockWarningResponseBody Body;
        
        public GetListStockWarningResponse() {
        }
        
        public GetListStockWarningResponse(PhoneApp1.HoSTC_Service.GetListStockWarningResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListStockWarningResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListStockWarningResult;
        
        public GetListStockWarningResponseBody() {
        }
        
        public GetListStockWarningResponseBody(string GetListStockWarningResult) {
            this.GetListStockWarningResult = GetListStockWarningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetList30StockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList30Stock", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetList30StockRequestBody Body;
        
        public GetList30StockRequest() {
        }
        
        public GetList30StockRequest(PhoneApp1.HoSTC_Service.GetList30StockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetList30StockRequestBody {
        
        public GetList30StockRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetList30StockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList30StockResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhoneApp1.HoSTC_Service.GetList30StockResponseBody Body;
        
        public GetList30StockResponse() {
        }
        
        public GetList30StockResponse(PhoneApp1.HoSTC_Service.GetList30StockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetList30StockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetList30StockResult;
        
        public GetList30StockResponseBody() {
        }
        
        public GetList30StockResponseBody(string GetList30StockResult) {
            this.GetList30StockResult = GetList30StockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HoSTC_ServiceSoapChannel : PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLiveSecurityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLiveSecurityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fPUT_THROUGHTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public fPUT_THROUGHTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fGetSTOCKROOMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public fGetSTOCKROOMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fUserOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public fUserOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLiveTotalMKTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLiveTotalMKTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListStockWarningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListStockWarningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetList30StockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetList30StockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoSTC_ServiceSoapClient : System.ServiceModel.ClientBase<PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap>, PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap {
        
        private BeginOperationDelegate onBeginGetLiveSecurityDelegate;
        
        private EndOperationDelegate onEndGetLiveSecurityDelegate;
        
        private System.Threading.SendOrPostCallback onGetLiveSecurityCompletedDelegate;
        
        private BeginOperationDelegate onBeginfPUT_THROUGHTDelegate;
        
        private EndOperationDelegate onEndfPUT_THROUGHTDelegate;
        
        private System.Threading.SendOrPostCallback onfPUT_THROUGHTCompletedDelegate;
        
        private BeginOperationDelegate onBeginfGetSTOCKROOMDelegate;
        
        private EndOperationDelegate onEndfGetSTOCKROOMDelegate;
        
        private System.Threading.SendOrPostCallback onfGetSTOCKROOMCompletedDelegate;
        
        private BeginOperationDelegate onBeginfUserOnlineDelegate;
        
        private EndOperationDelegate onEndfUserOnlineDelegate;
        
        private System.Threading.SendOrPostCallback onfUserOnlineCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLiveTotalMKTDelegate;
        
        private EndOperationDelegate onEndGetLiveTotalMKTDelegate;
        
        private System.Threading.SendOrPostCallback onGetLiveTotalMKTCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetListStockWarningDelegate;
        
        private EndOperationDelegate onEndGetListStockWarningDelegate;
        
        private System.Threading.SendOrPostCallback onGetListStockWarningCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetList30StockDelegate;
        
        private EndOperationDelegate onEndGetList30StockDelegate;
        
        private System.Threading.SendOrPostCallback onGetList30StockCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HoSTC_ServiceSoapClient() {
        }
        
        public HoSTC_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoSTC_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoSTC_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoSTC_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLiveSecurityCompletedEventArgs> GetLiveSecurityCompleted;
        
        public event System.EventHandler<fPUT_THROUGHTCompletedEventArgs> fPUT_THROUGHTCompleted;
        
        public event System.EventHandler<fGetSTOCKROOMCompletedEventArgs> fGetSTOCKROOMCompleted;
        
        public event System.EventHandler<fUserOnlineCompletedEventArgs> fUserOnlineCompleted;
        
        public event System.EventHandler<GetLiveTotalMKTCompletedEventArgs> GetLiveTotalMKTCompleted;
        
        public event System.EventHandler<GetListStockWarningCompletedEventArgs> GetListStockWarningCompleted;
        
        public event System.EventHandler<GetList30StockCompletedEventArgs> GetList30StockCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginGetLiveSecurity(PhoneApp1.HoSTC_Service.GetLiveSecurityRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLiveSecurity(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLiveSecurity(bool f_time, System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.GetLiveSecurityRequest inValue = new PhoneApp1.HoSTC_Service.GetLiveSecurityRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.GetLiveSecurityRequestBody();
            inValue.Body.f_time = f_time;
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginGetLiveSecurity(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.GetLiveSecurityResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndGetLiveSecurity(System.IAsyncResult result) {
            return base.Channel.EndGetLiveSecurity(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetLiveSecurity(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.GetLiveSecurityResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndGetLiveSecurity(result);
            return retVal.Body.GetLiveSecurityResult;
        }
        
        private System.IAsyncResult OnBeginGetLiveSecurity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool f_time = ((bool)(inValues[0]));
            return this.BeginGetLiveSecurity(f_time, callback, asyncState);
        }
        
        private object[] OnEndGetLiveSecurity(System.IAsyncResult result) {
            string retVal = this.EndGetLiveSecurity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLiveSecurityCompleted(object state) {
            if ((this.GetLiveSecurityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLiveSecurityCompleted(this, new GetLiveSecurityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLiveSecurityAsync(bool f_time) {
            this.GetLiveSecurityAsync(f_time, null);
        }
        
        public void GetLiveSecurityAsync(bool f_time, object userState) {
            if ((this.onBeginGetLiveSecurityDelegate == null)) {
                this.onBeginGetLiveSecurityDelegate = new BeginOperationDelegate(this.OnBeginGetLiveSecurity);
            }
            if ((this.onEndGetLiveSecurityDelegate == null)) {
                this.onEndGetLiveSecurityDelegate = new EndOperationDelegate(this.OnEndGetLiveSecurity);
            }
            if ((this.onGetLiveSecurityCompletedDelegate == null)) {
                this.onGetLiveSecurityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLiveSecurityCompleted);
            }
            base.InvokeAsync(this.onBeginGetLiveSecurityDelegate, new object[] {
                        f_time}, this.onEndGetLiveSecurityDelegate, this.onGetLiveSecurityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginfPUT_THROUGHT(PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfPUT_THROUGHT(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginfPUT_THROUGHT(System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequest inValue = new PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequestBody();
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginfPUT_THROUGHT(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndfPUT_THROUGHT(System.IAsyncResult result) {
            return base.Channel.EndfPUT_THROUGHT(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndfPUT_THROUGHT(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndfPUT_THROUGHT(result);
            return retVal.Body.fPUT_THROUGHTResult;
        }
        
        private System.IAsyncResult OnBeginfPUT_THROUGHT(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginfPUT_THROUGHT(callback, asyncState);
        }
        
        private object[] OnEndfPUT_THROUGHT(System.IAsyncResult result) {
            string retVal = this.EndfPUT_THROUGHT(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfPUT_THROUGHTCompleted(object state) {
            if ((this.fPUT_THROUGHTCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.fPUT_THROUGHTCompleted(this, new fPUT_THROUGHTCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void fPUT_THROUGHTAsync() {
            this.fPUT_THROUGHTAsync(null);
        }
        
        public void fPUT_THROUGHTAsync(object userState) {
            if ((this.onBeginfPUT_THROUGHTDelegate == null)) {
                this.onBeginfPUT_THROUGHTDelegate = new BeginOperationDelegate(this.OnBeginfPUT_THROUGHT);
            }
            if ((this.onEndfPUT_THROUGHTDelegate == null)) {
                this.onEndfPUT_THROUGHTDelegate = new EndOperationDelegate(this.OnEndfPUT_THROUGHT);
            }
            if ((this.onfPUT_THROUGHTCompletedDelegate == null)) {
                this.onfPUT_THROUGHTCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfPUT_THROUGHTCompleted);
            }
            base.InvokeAsync(this.onBeginfPUT_THROUGHTDelegate, null, this.onEndfPUT_THROUGHTDelegate, this.onfPUT_THROUGHTCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginfGetSTOCKROOM(PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfGetSTOCKROOM(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginfGetSTOCKROOM(System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequest inValue = new PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequestBody();
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginfGetSTOCKROOM(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndfGetSTOCKROOM(System.IAsyncResult result) {
            return base.Channel.EndfGetSTOCKROOM(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndfGetSTOCKROOM(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndfGetSTOCKROOM(result);
            return retVal.Body.fGetSTOCKROOMResult;
        }
        
        private System.IAsyncResult OnBeginfGetSTOCKROOM(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginfGetSTOCKROOM(callback, asyncState);
        }
        
        private object[] OnEndfGetSTOCKROOM(System.IAsyncResult result) {
            string retVal = this.EndfGetSTOCKROOM(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfGetSTOCKROOMCompleted(object state) {
            if ((this.fGetSTOCKROOMCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.fGetSTOCKROOMCompleted(this, new fGetSTOCKROOMCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void fGetSTOCKROOMAsync() {
            this.fGetSTOCKROOMAsync(null);
        }
        
        public void fGetSTOCKROOMAsync(object userState) {
            if ((this.onBeginfGetSTOCKROOMDelegate == null)) {
                this.onBeginfGetSTOCKROOMDelegate = new BeginOperationDelegate(this.OnBeginfGetSTOCKROOM);
            }
            if ((this.onEndfGetSTOCKROOMDelegate == null)) {
                this.onEndfGetSTOCKROOMDelegate = new EndOperationDelegate(this.OnEndfGetSTOCKROOM);
            }
            if ((this.onfGetSTOCKROOMCompletedDelegate == null)) {
                this.onfGetSTOCKROOMCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfGetSTOCKROOMCompleted);
            }
            base.InvokeAsync(this.onBeginfGetSTOCKROOMDelegate, null, this.onEndfGetSTOCKROOMDelegate, this.onfGetSTOCKROOMCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginfUserOnline(PhoneApp1.HoSTC_Service.fUserOnlineRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginfUserOnline(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginfUserOnline(System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.fUserOnlineRequest inValue = new PhoneApp1.HoSTC_Service.fUserOnlineRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.fUserOnlineRequestBody();
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginfUserOnline(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.fUserOnlineResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndfUserOnline(System.IAsyncResult result) {
            return base.Channel.EndfUserOnline(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndfUserOnline(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.fUserOnlineResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndfUserOnline(result);
            return retVal.Body.fUserOnlineResult;
        }
        
        private System.IAsyncResult OnBeginfUserOnline(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginfUserOnline(callback, asyncState);
        }
        
        private object[] OnEndfUserOnline(System.IAsyncResult result) {
            string retVal = this.EndfUserOnline(result);
            return new object[] {
                    retVal};
        }
        
        private void OnfUserOnlineCompleted(object state) {
            if ((this.fUserOnlineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.fUserOnlineCompleted(this, new fUserOnlineCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void fUserOnlineAsync() {
            this.fUserOnlineAsync(null);
        }
        
        public void fUserOnlineAsync(object userState) {
            if ((this.onBeginfUserOnlineDelegate == null)) {
                this.onBeginfUserOnlineDelegate = new BeginOperationDelegate(this.OnBeginfUserOnline);
            }
            if ((this.onEndfUserOnlineDelegate == null)) {
                this.onEndfUserOnlineDelegate = new EndOperationDelegate(this.OnEndfUserOnline);
            }
            if ((this.onfUserOnlineCompletedDelegate == null)) {
                this.onfUserOnlineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnfUserOnlineCompleted);
            }
            base.InvokeAsync(this.onBeginfUserOnlineDelegate, null, this.onEndfUserOnlineDelegate, this.onfUserOnlineCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginGetLiveTotalMKT(PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLiveTotalMKT(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLiveTotalMKT(System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequest inValue = new PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequestBody();
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginGetLiveTotalMKT(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndGetLiveTotalMKT(System.IAsyncResult result) {
            return base.Channel.EndGetLiveTotalMKT(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetLiveTotalMKT(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndGetLiveTotalMKT(result);
            return retVal.Body.GetLiveTotalMKTResult;
        }
        
        private System.IAsyncResult OnBeginGetLiveTotalMKT(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetLiveTotalMKT(callback, asyncState);
        }
        
        private object[] OnEndGetLiveTotalMKT(System.IAsyncResult result) {
            string retVal = this.EndGetLiveTotalMKT(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLiveTotalMKTCompleted(object state) {
            if ((this.GetLiveTotalMKTCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLiveTotalMKTCompleted(this, new GetLiveTotalMKTCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLiveTotalMKTAsync() {
            this.GetLiveTotalMKTAsync(null);
        }
        
        public void GetLiveTotalMKTAsync(object userState) {
            if ((this.onBeginGetLiveTotalMKTDelegate == null)) {
                this.onBeginGetLiveTotalMKTDelegate = new BeginOperationDelegate(this.OnBeginGetLiveTotalMKT);
            }
            if ((this.onEndGetLiveTotalMKTDelegate == null)) {
                this.onEndGetLiveTotalMKTDelegate = new EndOperationDelegate(this.OnEndGetLiveTotalMKT);
            }
            if ((this.onGetLiveTotalMKTCompletedDelegate == null)) {
                this.onGetLiveTotalMKTCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLiveTotalMKTCompleted);
            }
            base.InvokeAsync(this.onBeginGetLiveTotalMKTDelegate, null, this.onEndGetLiveTotalMKTDelegate, this.onGetLiveTotalMKTCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginGetListStockWarning(PhoneApp1.HoSTC_Service.GetListStockWarningRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListStockWarning(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetListStockWarning(System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.GetListStockWarningRequest inValue = new PhoneApp1.HoSTC_Service.GetListStockWarningRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.GetListStockWarningRequestBody();
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginGetListStockWarning(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.GetListStockWarningResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndGetListStockWarning(System.IAsyncResult result) {
            return base.Channel.EndGetListStockWarning(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetListStockWarning(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.GetListStockWarningResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndGetListStockWarning(result);
            return retVal.Body.GetListStockWarningResult;
        }
        
        private System.IAsyncResult OnBeginGetListStockWarning(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetListStockWarning(callback, asyncState);
        }
        
        private object[] OnEndGetListStockWarning(System.IAsyncResult result) {
            string retVal = this.EndGetListStockWarning(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListStockWarningCompleted(object state) {
            if ((this.GetListStockWarningCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListStockWarningCompleted(this, new GetListStockWarningCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListStockWarningAsync() {
            this.GetListStockWarningAsync(null);
        }
        
        public void GetListStockWarningAsync(object userState) {
            if ((this.onBeginGetListStockWarningDelegate == null)) {
                this.onBeginGetListStockWarningDelegate = new BeginOperationDelegate(this.OnBeginGetListStockWarning);
            }
            if ((this.onEndGetListStockWarningDelegate == null)) {
                this.onEndGetListStockWarningDelegate = new EndOperationDelegate(this.OnEndGetListStockWarning);
            }
            if ((this.onGetListStockWarningCompletedDelegate == null)) {
                this.onGetListStockWarningCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListStockWarningCompleted);
            }
            base.InvokeAsync(this.onBeginGetListStockWarningDelegate, null, this.onEndGetListStockWarningDelegate, this.onGetListStockWarningCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.BeginGetList30Stock(PhoneApp1.HoSTC_Service.GetList30StockRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetList30Stock(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetList30Stock(System.AsyncCallback callback, object asyncState) {
            PhoneApp1.HoSTC_Service.GetList30StockRequest inValue = new PhoneApp1.HoSTC_Service.GetList30StockRequest();
            inValue.Body = new PhoneApp1.HoSTC_Service.GetList30StockRequestBody();
            return ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).BeginGetList30Stock(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp1.HoSTC_Service.GetList30StockResponse PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap.EndGetList30Stock(System.IAsyncResult result) {
            return base.Channel.EndGetList30Stock(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetList30Stock(System.IAsyncResult result) {
            PhoneApp1.HoSTC_Service.GetList30StockResponse retVal = ((PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap)(this)).EndGetList30Stock(result);
            return retVal.Body.GetList30StockResult;
        }
        
        private System.IAsyncResult OnBeginGetList30Stock(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetList30Stock(callback, asyncState);
        }
        
        private object[] OnEndGetList30Stock(System.IAsyncResult result) {
            string retVal = this.EndGetList30Stock(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetList30StockCompleted(object state) {
            if ((this.GetList30StockCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetList30StockCompleted(this, new GetList30StockCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetList30StockAsync() {
            this.GetList30StockAsync(null);
        }
        
        public void GetList30StockAsync(object userState) {
            if ((this.onBeginGetList30StockDelegate == null)) {
                this.onBeginGetList30StockDelegate = new BeginOperationDelegate(this.OnBeginGetList30Stock);
            }
            if ((this.onEndGetList30StockDelegate == null)) {
                this.onEndGetList30StockDelegate = new EndOperationDelegate(this.OnEndGetList30Stock);
            }
            if ((this.onGetList30StockCompletedDelegate == null)) {
                this.onGetList30StockCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetList30StockCompleted);
            }
            base.InvokeAsync(this.onBeginGetList30StockDelegate, null, this.onEndGetList30StockDelegate, this.onGetList30StockCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap CreateChannel() {
            return new HoSTC_ServiceSoapClientChannel(this);
        }
        
        private class HoSTC_ServiceSoapClientChannel : ChannelBase<PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap>, PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap {
            
            public HoSTC_ServiceSoapClientChannel(System.ServiceModel.ClientBase<PhoneApp1.HoSTC_Service.HoSTC_ServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLiveSecurity(PhoneApp1.HoSTC_Service.GetLiveSecurityRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLiveSecurity", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.GetLiveSecurityResponse EndGetLiveSecurity(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.GetLiveSecurityResponse _result = ((PhoneApp1.HoSTC_Service.GetLiveSecurityResponse)(base.EndInvoke("GetLiveSecurity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginfPUT_THROUGHT(PhoneApp1.HoSTC_Service.fPUT_THROUGHTRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("fPUT_THROUGHT", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponse EndfPUT_THROUGHT(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponse _result = ((PhoneApp1.HoSTC_Service.fPUT_THROUGHTResponse)(base.EndInvoke("fPUT_THROUGHT", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginfGetSTOCKROOM(PhoneApp1.HoSTC_Service.fGetSTOCKROOMRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("fGetSTOCKROOM", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponse EndfGetSTOCKROOM(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponse _result = ((PhoneApp1.HoSTC_Service.fGetSTOCKROOMResponse)(base.EndInvoke("fGetSTOCKROOM", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginfUserOnline(PhoneApp1.HoSTC_Service.fUserOnlineRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("fUserOnline", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.fUserOnlineResponse EndfUserOnline(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.fUserOnlineResponse _result = ((PhoneApp1.HoSTC_Service.fUserOnlineResponse)(base.EndInvoke("fUserOnline", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLiveTotalMKT(PhoneApp1.HoSTC_Service.GetLiveTotalMKTRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLiveTotalMKT", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponse EndGetLiveTotalMKT(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponse _result = ((PhoneApp1.HoSTC_Service.GetLiveTotalMKTResponse)(base.EndInvoke("GetLiveTotalMKT", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetListStockWarning(PhoneApp1.HoSTC_Service.GetListStockWarningRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetListStockWarning", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.GetListStockWarningResponse EndGetListStockWarning(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.GetListStockWarningResponse _result = ((PhoneApp1.HoSTC_Service.GetListStockWarningResponse)(base.EndInvoke("GetListStockWarning", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetList30Stock(PhoneApp1.HoSTC_Service.GetList30StockRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetList30Stock", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp1.HoSTC_Service.GetList30StockResponse EndGetList30Stock(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp1.HoSTC_Service.GetList30StockResponse _result = ((PhoneApp1.HoSTC_Service.GetList30StockResponse)(base.EndInvoke("GetList30Stock", _args, result)));
                return _result;
            }
        }
    }
}
